### ISSUE TITLE
Exception due to "try/else" when pyproj available

### ISSUE THREAD

**Issue by stefraynaud** [pygridgen/pygridgen#49]
Hi,

by definition, the following `else` is executed everytime no exception is intercepted by the `try` statement. Since it raises itself an exception, the code fails if pyproj is available, isn't it?
https://github.com/pygridgen/pygridgen/blob/dc8f7c7bc4204f312389ffb7c5295bd14d031479/pygridgen/grid.py#L634
The latest conda package is based on this code.

**Comment by phobson** [comment]
@stefraynaud 

Thanks for reporting the issue. I have to confess, I'm almost always working in projected coordinates, so I've never had to use the `CGrid_geo` class. 

If you could recommend a fix and add a test in PR, that'd be most helpful.

**Comment by phobson** [comment]
clsoed by #51
